config/routes.rb
Svp::Application.routes.draw do

  resources :case_studies

  resources :members

  resources :ventures

  resources :programmes

  root :to => 'high_voltage/pages#show', id: 'home'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

end

app/models/programme.rb
class Programme < ActiveRecord::Base
  attr_accessible :description, :duration, :founded, :funding_offered, :location, :name, :prog_type, :website_url, :next_prog, :prog_image, :continent, :country, :city, :long, :lat

  has_and_belongs_to_many :users
  has_and_belongs_to_many :ventures

  mount_uploader :prog_image, ProgImageUploader

  # mount_uploader :prog_image, ProgImageUploader
end

app/controllers/programmes_controller.rb
class ProgrammesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /programmes
  # GET /programmes.json
  def index
    @venture = Venture.new
    @programmes = Programme.all

    # finding lat and lng of locations
    #Can drop once new data is inputted online and lat and lng saved when individual programmes created
    # @programmes.each do |programme|
    #   city = programme.city.gsub(/ /, '+')
    #   country = programme.country.gsub(/ /, '+') 
    #   continent = programme.continent.gsub(/ /, '+') 
    #   prog_coords = HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{city}+#{country}+#{continent}&key=AIzaSyAJ5DQQKqw8alS7ytLsWZfm0fZEFUptN20")
    #   programme.lat = prog_coords["results"][0]["geometry"]["location"]["lat"]
    #   programme.long = prog_coords["results"][0]["geometry"]["location"]["lng"]
    #   programme.save
    # end

    gon.programmes = @programmes


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programmes.to_json(include: [:ventures]) }
    end
  end

  # GET /programmes/1
  # GET /programmes/1.json
  def show
    @programme = Programme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @programme }
    end
  end

  # GET /programmes/new
  # GET /programmes/new.json
  def new
    @programme = Programme.new
    gon.programmes = Programme.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @programme }
    end
  end

  # GET /programmes/1/edit
  def edit
    gon.programmes = Programme.all

    @programme = Programme.find(params[:id])
  end

  # POST /programmes
  # POST /programmes.json
  def create
    @programme = Programme.new(params[:programme])
    @programme.users.push(current_user)

    city = @programme.city.gsub(/ /, '+')
    country = @programme.country.gsub(/ /, '+') 
    continent = @programme.continent.gsub(/ /, '+') 

    prog_coords = HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{city}+#{country}+#{continent}&key=AIzaSyBz8y-Bd8XIaaIPyEyhTV1LmcCTfxVhgnA")
    @programme.lat = prog_coords["results"][0]["geometry"]["location"]["lat"]
    @programme.long = prog_coords["results"][0]["geometry"]["location"]["lng"]
    respond_to do |format|
      if @programme.save
        format.html { redirect_to @programme, notice: 'Programme was successfully created.' }
        format.json { render json: @programme, status: :created, location: @programme }
      else
        format.html { render action: "new" }
        format.json { render json: @programme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programmes/1
  # PUT /programmes/1.json
  def update
    gon.programmes = Programme.all
    @programme = Programme.find(params[:id])
    city = @programme.city.gsub(/ /, '+')
    country = @programme.country.gsub(/ /, '+') 
    continent = @programme.continent.gsub(/ /, '+') 
    prog_coords = HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{city}+#{country}+#{continent}&key=AIzaSyDSJmvMFOXZEZxJ8X6aP7SFyuVWH_RNI0Y")
    @programme.lat = prog_coords["results"][0]["geometry"]["location"]["lat"]
    @programme.long = prog_coords["results"][0]["geometry"]["location"]["lng"]

    respond_to do |format|
      if @programme.update_attributes(params[:programme])
        # format.html { redirect_to @programme, notice: 'Programme was successfully updated.' }
        format.html { redirect_to member_path(current_user.id), notice: 'Programme was successfully updated.' }

        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @programme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programmes/1
  # DELETE /programmes/1.json
  def destroy
    @programme = Programme.find(params[:id])
    @programme.destroy

    respond_to do |format|
      format.html { redirect_to programmes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/programmes_helper.rb
module ProgrammesHelper

  def getImage(user)
    if user.user_image == nil
      img = user.image
    else
      img = user.user_image
    end
    img
  end
end

app/views/programmes/_form.html.haml
.editprog_controller{"ng-controller" => "progController"}

  .form_background

  = form_for @programme do |f|
    - if @programme.errors.any?
      #error_explanation
        %h2= "#{pluralize(@programme.errors.count, "error")} prohibited this programme from being saved:"
        %ul
          - @programme.errors.full_messages.each do |msg|
            %li= msg
    .form_container
      .prog_form_first{'ng-hide' => 'showingSecondForm || showingThirdForm' }
        %a{:href => "/"}
          %img{:src => asset_path("close_button.png")}/
        .field
          = f.label "Programme Name"
          %br
          = f.text_field :name
        .field
          = f.label "Programme Type"
          %br
          / = f.text_field :prog_type
          = f.select(:prog_type, :options => ["Accelerator", "Incubator", "Competition", "Bootcamp"])
        .field
          = f.label :location
          %br
          = f.text_field :city, :placeholder => "City"
          = f.text_field :country, :placeholder => "Country"
          = f.text_field :continent, :placeholder => "Continent"
        .first_next{'ng-click' => 'showSecondForm()'}
          NEXT
    .form_container
      .prog_form_second{'ng-show'=>'showingSecondForm'}
        %a{:href => "/"}
          %img{:src => asset_path("close_button.png")}/
        .field
          = f.label :description
          %br
          = f.text_area :description, :rows => 10
        .first_back{'ng-click' => 'hideSecondForm()'}
          BACK
        .second_next{'ng-click'=>'showThirdForm()'}
          NEXT
    .form_container
      .prog_form_third{'ng-show'=>'showingThirdForm'}
        %a{:href => "/"}
          %img{:src => asset_path("close_button.png")}/
        .field
          = f.label :duration
          %br
          = f.text_field :duration
        .field
          = f.label :funding_offered
          %br
          = f.number_field :funding_offered
        .field
          = f.label :website_url
          %br
          = f.text_field :website_url
        .field
          = f.label :founded
          %br
          = f.number_field :founded
        .field
          = f.label :prog_image
          %br
          = f.file_field :prog_image
        .second_back{'ng-click' => 'hideThirdForm()'}
          BACK
        .actions
          = f.submit 'Save', :class => "submit_button"

app/views/programmes/edit.html.haml
%h1 Editing programme

= render 'form'

= link_to 'Show', @programme
\|
= link_to 'Back', programmes_path

app/views/programmes/index.html.haml
.prog_controller{"ng-controller" => "progController"}
 
  .nav_and_list{'ng-show' => 'showingNavAndList'}
    
    %google-map{:center=>"map.center", :zoom=>"map.zoom"}
      %markers{:models=>"markers", :coords=>"'self'", :options => "'options'"}
        %windows{:show => "show"}
          %div{"ng-non-bindable"=>""}{{title}}

    .filter_nav
      .nav_block
        %input{'ng-model'=>"searchText", "placeholder"=>"Search for programmes"}
        .filter_title
          Filter by:
        .prog_type_button{'ng-click' => 'progFilterClicked()', "ng-class"=>"{active: prog_list_invisible}"}
          Programme Type
        .geog_type_button{'ng-click' => 'contFilterClicked()', "ng-class"=>"{active: continent_list_invisible}"}
          Geography
        %ul#prog_type_list{'ng-class'=>'prog_list'}
          %li{'ng-repeat' => 'programme_type in programme_types', 'ng-show' => 'prog_list_invisible', 'ng-click' => 'programmeClicked(programme_type)', "ng-class"=>"{active: (programme_type_clicked == programme)}", 'class'=>'prog_type'}
            {{programme_type}}
        %ul#continent_list
          %li{'ng-repeat' => 'continent in continents', 'ng-click' => 'continentClicked(continent)', 'ng-show' => 'continent_list_invisible', 'class'=>'continent_button'} 
            {{continent}}
        %ul#country_list
          %li{'ng-repeat' => 'country in countries', 'ng-show' => "showingCountries", 'ng-click' => 'countryClicked(country)', 'class'=>'country_button'}
            {{country}}
        
    .prog_list{'ng-hide' => "showingFilteredResults" || "showingProfile"}
      .prog_list_instance{'ng-repeat'=>"programme in programmes | filter:searchText", 'ng-click' => 'showProgramme(programme)'}
 
        %img(src="{{programme.prog_image.url}}")
        .prog_list_instance_text
          %h2
            {{programme.name}}
          %p
            {{programme.prog_type}}
            %span || {{programme.city}}

    .filtered-list{'ng-show' => 'showingFilteredResults'}
      .prog_list_instance{'ng-repeat'=>"programme in programmes | filter: searchText", 'ng-click' => 'showProgramme(programme)'}   
        %img(src="{{programme.prog_image.url}}")
        .prog_list_instance_text
          %h2
            {{programme.name}}
          %p
            {{programme.prog_type}}
            %span || {{programme.city}}

  .profile{'ng-hide' => '!showingProfile'}
    .showing-selected-programme

app/views/programmes/new.html.haml
= render 'form'

app/views/programmes/show.html.haml
.profile
  %p{:notice => "notice"}
  .profile_image
    %img{:src => @programme.prog_image}
  %br/
  .profile_name
    =@programme.name
  %br/
  .profile_description
    =@programme.description
  %br/
  .profile_type
    Type: 
    =@programme.prog_type
  %br/
  .profile_duration
    Duration:
    =@programme.duration
  %br/
  .profile_funding
    Funding offered:
    =@programme.funding_offered
  %br/
  .profile_url
    %a{:href => "=@programme.website_url"} Website
  .edit_button{"ng-click" => "editProfile(programme)"}
    EDIT

    / = link_to 'Destroy', programme_path(@programme), :method => :delete