config/routes.rb
Svp::Application.routes.draw do

  resources :case_studies

  resources :members

  resources :ventures

  resources :programmes

  root :to => 'high_voltage/pages#show', id: 'home'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

end

app/views/pages/about.html.haml
.about_us_cont{"ng-controller" => "progController"}
  = content_for :title, "About us"
  .about_us_page
    .about_us_container
      .about_us 
        Nesta is an innovation charity with a mission to help people and organisations bring great ideas to life.

        We are dedicated to supporting ideas that can help improve all our lives, with activities ranging from early stage investment to in-depth research and practical programmes.
         
        We don’t work alone - we rely on the strength of the partnerships we form with you and with others to make change happen.
         
        Find out more about our mission below, meet the people that work here, and see how you can become part of the team.
    .nesta_video
      %iframe{:allowfullscreen => "", :frameborder => "0", :height => "480", :src => "//www.youtube.com/embed/pJQtjkl7L1I", :width => "450"}

    .twitterfeed_panel  
      %a.twitter-timeline{"data-widget-id" => "512015464860364801", :href => "https://twitter.com/nesta_uk"} Tweets by @nesta_uk
      :javascript
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
    %br
    %br
    %h2
      Learn more about incubation for social good
    %object{'data'=>"http://www.nesta.org.uk/sites/default/files/good_incubation_wv.pdf", 'type'=>"application/pdf", 'width'=>"800", 'height'=>"1000"}

app/views/pages/about_progs.html.haml
.abount_progs_page.cf
  .flip-container{:ontouchstart => "this.classList.toggle('hover');"}
    .flipper
      .front
        Accelerator
      .back
        An accelerator takes single-digit chunks of equity in externally developed ideas in return for small amounts of capital and mentorship. They’re generally truncated into a three to four month program at the end of which the start-ups ‘graduate’.


  .flip-container{:ontouchstart => "this.classList.toggle('hover');"}
    .flipper
      .front
        Incubator
      .back
        An incubator brings in an external management team to manage an idea that was developed internally. Those ideas can gestate for much longer periods of time and the incubator takes a much larger amount of equity compared to accelerators.

  .flip-container{:ontouchstart => "this.classList.toggle('hover');"}
    .flipper
      .front
        Competition
      .back
        A competition is an opportunity for entrepreneurs to pitch their ideas to a panel of expert judges with the winner recieving prize money amongst other benefits.

  .flip-container{:ontouchstart => "this.classList.toggle('hover');"}
    .flipper
      .front
        Bootcamp
      .back
        Austin four loko bitters, before they sold out dreamcatcher seitan Odd Future Pinterest Echo Park disrupt salvia Etsy banjo. Semiotics typewriter 90's single-origin coffee sustainable migas American Apparel flannel, Intelligentsia readymade.

app/views/pages/home.html.haml
.home_panel
  
  .progs_panel
    %img{:src => asset_path( 'sv2.jpg' )}/
    .panel_text
      %h2
        View 
        %span Programmes
      %p
        Filter programmes by location and type
      = link_to 'View Programmes', programmes_path

  .edit_prog_panel
    %img{:src => asset_path( 'svafrica.jpg' )}/
    .panel_text
      %h2
        Manage 
        %span Your Programmes
      -if current_user
        %p
          Update details on your programme
        = link_to 'Manage Your Programme', member_path(current_user.id)
      -else
        %p
          Update details on your programme
        = link_to 'Manage Your Programme', new_user_session_path

  .aboutus_panel
    %img{:src => asset_path( 'nesta.png' )}/
    .panel_text
      %h2
        About 
        %span Nesta
      %p
        Learn more about Nesta and our work on social ventures
      = link_to 'About Nesta', page_path('about')
  .cases_panel
    %img{:src => asset_path( 'lifelab1.jpg' )}/
    .panel_text
      %h2
        About Social Venture 
        %span Programmes
      %p
        Learn more about the programme types featured
      = link_to 'About Social Venture Programmes', page_path('about_progs')
  .addprog_panel
    %img{:src => asset_path( 'sv1.jpg' )}/
    .panel_text
      %h2
        Add 
        %span A Programme
      %p
        Have your programme listed on SVP
      = link_to 'Add A Programme', new_programme_path
  

  



  

app/views/pages/terms_and_conditions.html.haml
TERMS AND CONDITIONS HERE