config/routes.rb
Svp::Application.routes.draw do

  resources :case_studies

  resources :members

  resources :ventures

  resources :programmes

  root :to => 'high_voltage/pages#show', id: 'home'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

end

app/models/member.rb
class Member < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter :authenticate_user!

  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    
    gon.programmes = Programme.all
    gon.current_user = current_user
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.haml
= form_for @member do |f|
  - if @member.errors.any?
    #error_explanation
      %h2= "#{pluralize(@member.errors.count, "error")} prohibited this member from being saved:"
      %ul
        - @member.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/members/edit.html.haml
%h1 Editing member

= render 'form'

= link_to 'Show', @member
\|
= link_to 'Back', members_path

app/views/members/index.html.haml
%h1 Listing members

%table
  %tr
    %th
    %th
    %th

  - @members.each do |member|
    %tr
      %td= link_to 'Show', member
      %td= link_to 'Edit', edit_member_path(member)
      %td= link_to 'Destroy', member, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Member', new_member_path

app/views/members/new.html.haml
%h1 New member

= render 'form'

= link_to 'Back', members_path

app/views/members/show.html.haml
.manage_progs{"ng-controller" => "progController"}
  .manage_progs_page{'ng-hide'=>'hidingManageProgs'}

    %p#notice= notice
    .manage_programme_instance{'ng-repeat'=>'programme in current_user_programmes'}
      %img(src="{{programme.prog_image.url}}")
      .member_progs_content 
        .member_prog_name
          {{programme.name}}
        .member_prog_description
          {{programme.description}}
        %br
        %br
        .member_prog_type
          {{programme.prog_type}}
          , founded in 
          {{programme.founded}}
        %br
        .member_prog_buttons
          .button#showing-venture-button{'ng-click'=>"showVentures()"}
            Show Ventures
          .button{'ng-click'=>"addVentureButton(programme)"}
            Add a Venture
          .button{'ng-click'=>"editProgrammeButton(programme)"}
            Edit Programme
        / .button{'ng-click'=>"editProgrammeButton(#{programme.to_json})"}
      .prog_list{'ng-show'=>"showingVentures"}
        / -programme.ventures.each do |venture|
        .prog_list_instance{'ng-repeat'=>'venture in programme.ventures', 'ng-click' => 'showVenture(venture)'}
          %img.venture_img(src="http://saltlake.impacthub.net/wp-content/uploads/sites/97/2013/10/collaborate-768x503.jpg")
          .prog_list_instance_text
            %h2
              {{venture.name}}
            %p
              {{venture.org_type}}
              %span || {{venture.location}}
          
          
      / = link_to 'Edit', edit_member_path(@user)
      
      / = link_to 'Back', members_path
  .programme-form{'ng-show' => 'editingProgramme'}
    .edit-programme-form
  .venture-form{'ng-show' => 'addingVenture'}
    .add-venture-form